# Generated by Django 6.0.4 on 2026-04-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='complaint_documents/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
